adobe/aem-cloud-service-source-migration

packages/dispatcher-converter/README.md
packages/dispatcher-converter/src/converter/singleFilesConverter.js
packages/dispatcher-converter/src/util/FileOperations.js

Fixing path issue, include rewrite file content and closing section check

---

packages/repository-modernizer/executors/config.yaml
packages/repository-modernizer/junit.xml
packages/repository-modernizer/resources/pom.xml
packages/repository-modernizer/src/restructure-filters.js
packages/repository-modernizer/src/restructure-pom.js
packages/repository-modernizer/src/util/constants.js
packages/repository-modernizer/test/config.yaml
packages/repository-modernizer/test/resources/pom.xml
packages/repository-modernizer/test/restructure-pom.test.js

Added fix parent pom and filters in pom

---

packages/dispatcher-converter/test/FileOperationsTest.js

Fixing test, failed due to added check while getting content from file

---

packages/index-converter/README.md

Correction in README of index-converter

---

packages/repository-modernizer/README.md
packages/repository-modernizer/executors/config.yaml
packages/repository-modernizer/package.json
packages/repository-modernizer/resources/all/pom.xml
packages/repository-modernizer/resources/ui.apps/pom.xml
packages/repository-modernizer/resources/ui.config/pom.xml
packages/repository-modernizer/resources/ui.content/pom.xml
packages/repository-modernizer/src/create-base-project-structure.js
packages/repository-modernizer/src/restructure-pom.js
packages/repository-modernizer/src/util/constants.js
packages/repository-modernizer/src/util/pom-manipulation-util.js

PR contains multiple bug fixes as follow-:
CQ-4314507 - [Adobe-IO][Repository Modernizer] Generated maven projects missing version
CQ-4314505 - [Adobe-IO][Repository Modernizer] Does not include new maven projects as modules
CQ-4309347 - [Repo-modernizer] Directly embed core bundles into all pom
--

CQ-4314505,CQ-4314507,CQ-4309347 : Multiple bug fixes

---

packages/repository-modernizer/src/create-base-project-structure.js
packages/repository-modernizer/src/restructure-pom.js
packages/repository-modernizer/src/util/constants.js
packages/repository-modernizer/test/config.yaml
packages/repository-modernizer/test/restructure-pom.test.js

CQ-4309347 [Repo-modernizer] Directly embed core bundles into all pom

CQ-4309347 [Repo-modernizer] Directly embed core bundles into all pom

---

packages/repository-modernizer/executors/repository-modernizer.js
packages/repository-modernizer/index.js
packages/repository-modernizer/src/create-base-project-structure.js
packages/repository-modernizer/src/restructure-filters.js
packages/repository-modernizer/src/util/constants.js

CQ-4313028 - Migrate include/exclude filters with modes
CQ-4315298 - [Adobe-IO][Repository Modernizer Add error message for incorrect config file

CQ-4313028,CQ-4315298: multiple fixes

---

packages/dispatcher-converter/src/util/FileOperations.js

CQ-4314653 Fixing unbalanced { issue

---

packages/dispatcher-converter/src/converter/amsDispatcherConfigConverter.js
packages/dispatcher-converter/src/converter/singleFilesConverter.js
packages/dispatcher-converter/src/util/FileOperations.js
packages/dispatcher-converter/test/FileOperationsTest.js

CQ-4314851 Dispatcher Converter Improvements and Bug Fixes

---

packages/index-converter/README.md

Adding known limitations

---

packages/index-converter/index.js
packages/index-converter/src/index-converter.js
packages/index-converter/src/util/constants.js
packages/index-converter/src/util/xml-processing-util.js

-Index converter does not considers filter analyzers
-Index converter report - Details on what to do. with property index

Index converter does not considers filter analyzers

---

.changeset/shy-ligers-switch.md

Creating change set file for release

---

packages/dispatcher-converter/src/converter/singleFilesConverter.js

CQ-4321146 Fixing vhosts on ports other than 80

---

packages/dispatcher-converter/src/converter/amsDispatcherConfigConverter.js
packages/dispatcher-converter/src/util/FileOperations.js
packages/dispatcher-converter/test/FileOperationsTest.js

PR contains a fix for [CQ-4321398] Fix symlink logic for AMS dispatcher converter and also incorporates test cases for the introduced changes.
- Added Unit Tests
- Manual testing with customer data

CQ-4321398 Fix symlink logic for AMS dispatcher converter

---

.travis.yml
codecov.yml

CQ-4320891

---

packages/dispatcher-converter/test/FileOperationsTest.js

fix failing tests

---

.travis.yml
codecov.yml
packages/dispatcher-converter/test/FileOperationsTest.js

PR contains a fix for CQ-4320891 Integration of Code Coverage Utility with Github & failing test cases fixes. Since this is a monorepo, we need to set up flags for codecov & cd into each directory upload coverage.

Integration of Code Coverage Utility with Github & test case fixes

---

.changeset/flat-boats-promise.md
.changeset/hungry-ears-grab.md
.changeset/loud-foxes-sleep.md
package.json

Added changeset files for each packages

---

packages/dispatcher-converter/package.json
packages/index-converter/package.json

include coverage script for failed coverage job

---

.github/workflows/codecovCoverage.yml
packages/dispatcher-converter/src/converter/amsDispatcherConfigConverter.js
packages/dispatcher-converter/src/converter/singleFilesConverter.js
packages/dispatcher-converter/src/util/FileOperations.js
packages/index-converter/index.js
packages/index-converter/src/index-converter.js
packages/index-converter/src/util/index-converter-util.js
packages/index-converter/test/ensure-definition-converter-test.js
packages/index-converter/test/index-converter-util-test.js
packages/index-converter/test/map-processing-util-test.js
packages/index-converter/test/xml-processing-util-test.js
packages/repository-modernizer/resources/pom.xml
packages/repository-modernizer/resources/ui.apps.structure/pom.xml
packages/repository-modernizer/src/restructure-pom.js
packages/repository-modernizer/src/util/constants.js
packages/repository-modernizer/src/util/pom-manipulation-util.js

This PR contains changes for 
- Reported build issues after conversion of the code using repository modernizer
- added test cases
- linting issues

Discrepancies in POM XML after transformation

---

packages/repository-modernizer/src/restructure-config.js
packages/repository-modernizer/test/resources/com.adobe.config.test.cfg.json
packages/repository-modernizer/test/resources/com.adobe.config.test.xml

- PR contains changes for Multivalued and Datatypes not transformed properly in Repo Modernizer
- related test cases changes

CQ-4324531 : Multivalued and Datatypes issue

---

packages/repository-modernizer/README.md
packages/repository-modernizer/resources/pom.xml
packages/repository-modernizer/src/create-base-project-structure.js
packages/repository-modernizer/src/restructure-pom.js
packages/repository-modernizer/test/create-base-project-structure.test.js
packages/repository-modernizer/test/multiProjectConfig.yaml
packages/repository-modernizer/test/restructure-pom.test.js

PR contains changes to create reactor poms for each individual projects in case of multi-project repo & related changes to test cases

CQ-4309362 : [Repo-modernizer] Create reactor poms for each individual projects

---

.changeset/famous-ants-beg.md

add changelist file for repo-modernizer

---

packages/repository-modernizer/src/restructure-config.js
packages/repository-modernizer/src/util/constants.js
packages/repository-modernizer/test/resources/com.adobe.config.test.cfg.json
packages/repository-modernizer/test/resources/com.adobe.config.test.xml

During transformation , the configs like "\{0,date,yyyy-MM-dd HH:mm:ss.SSS} {4} [{3}] {5}" for log manager factory was not getting migrated properly.

CQ-4325182  : LogManager.factory.config issue

---

packages/repository-modernizer/resources/all/pom.xml
packages/repository-modernizer/resources/ui.apps/pom.xml
packages/repository-modernizer/resources/ui.config/pom.xml
packages/repository-modernizer/resources/ui.content/pom.xml
packages/repository-modernizer/src/restructure-pom.js
packages/repository-modernizer/src/util/constants.js
packages/repository-modernizer/src/util/pom-manipulation-util.js
packages/repository-modernizer/test/pom-manipulation-util.test.js

The PR contains changes for :
1.  aem.sdk.api version should be fetched from parent.
2. plugins used across should have version fetched from reactor pom for other poms.

Review Improvements for repository modernizer tool

---

packages/repository-modernizer/README.md
packages/repository-modernizer/executors/config.yaml
packages/repository-modernizer/src/create-base-project-structure.js
packages/repository-modernizer/src/restructure-config.js
packages/repository-modernizer/src/restructure-content.js
packages/repository-modernizer/src/restructure-filters.js
packages/repository-modernizer/src/restructure-pom.js
packages/repository-modernizer/test/create-base-project-structure.test.js
packages/repository-modernizer/test/projectWithSubProjectConfig.yaml
packages/repository-modernizer/test/resources/sub-project/pom.xml
packages/repository-modernizer/test/restructure-filters.test.js
packages/repository-modernizer/test/restructure-pom.test.js

PR contains changes for transforming sub-projects along with main projects if they are configured

CQ-4325771 : Sub Projects not getting transformed properly

---

.github/workflows/codecovCoverage.yml
.github/workflows/publish.yml

The last run failed due to an incompatible node engine version error on Github Linux machine.
https://github.com/adobe/aem-cloud-service-source-migration/runs/2849188757

fix yarn engine failures

---

packages/dispatcher-converter/src/converter/singleFilesConverter.js

Check for the value to be set, if not set, do not process.
Issue: #48 
Prevent future failures during use.
Tested on exemplar projects.

Fix for error on empty configuration.

---

.changeset/dry-maps-sin.md
.changeset/wild-trains-roll.md

Added changelist file for sub-packages

---

packages/dispatcher-converter/executors/main.js
packages/dispatcher-converter/executors/singleFileMain.js
packages/dispatcher-converter/src/converter/amsDispatcherConfigConverter.js
packages/dispatcher-converter/src/converter/singleFilesConverter.js
packages/repository-modernizer/index.js

PR contains changes around checking required variables present in config before executing to stop it from falling in between.
"==" will check for undefined and null both hence "===" is changed to "=="

CQ-4326843 : null & undefined check rectification

---

packages/dispatcher-converter/src/util/FileOperations.js

CQ-4327400 : Dispatcher Converter Tool - Unilever Issue

---

packages/dispatcher-converter/src/util/FileOperations.js
packages/dispatcher-converter/test/FileOperationsTest.js

CQ-4327400 : RewriteRules getting commented

---

packages/dispatcher-converter/src/converter/singleFilesConverter.js

CQ-4327568 : [Dispatcher Converter] Issue in the conversion when duplicate farm files are present

---

packages/dispatcher-converter/src/converter/singleFilesConverter.js
packages/dispatcher-converter/src/util/FileOperations.js

Issue with `vhostsToConvert` & $Include property

---

packages/dispatcher-converter/src/converter/singleFilesConverter.js
packages/dispatcher-converter/src/util/constants.js

CQ-4328889 : [Dispatcher Converter] Rules file inclusion issue.

---

packages/dispatcher-converter/src/converter/amsDispatcherConfigConverter.js
packages/dispatcher-converter/src/util/FileOperations.js
packages/dispatcher-converter/test/FileOperationsTest.js

CQ-4315907 : Customisation required for existing custom-variables into global.vars for AMS configs

---

packages/commons/src/util.js
packages/dispatcher-converter/executors/main.js
packages/dispatcher-converter/src/converter/amsDispatcherConfigConverter.js

CQ-4329547 : [Dispatcher converter] Error running the tool on AMS configs which includes sym-linked files, invalid includes

---

.changeset/lazy-ducks-invent.md
.changeset/sixty-years-itch.md

Release dispatcher version 1.5.0

---

packages/dispatcher-converter/src/util/FileOperations.js
packages/dispatcher-converter/test/FileOperationsTest.js
packages/dispatcher-converter/test/newtestoldfile.txt
packages/repository-modernizer/executors/config.yaml

Fix regression in duplicate detection logic.
* manual testing

CQ-4357130: Duplicate variables present in consolidated custom vars file

---

.changeset/fluffy-turkeys-wink.md

Releasing dispatcher converter patch.

Release dispatcher-converter version 1.5.1

---

packages/dispatcher-converter/test/newtestoldfile.txt

Publishing failed because the test file was deleted in the [commit](https://github.com/adobe/aem-cloud-service-source-migration/commit/b0bd5f72a5ec51be7a13dc4c601214273c9b1ebd) 
```
error: The following untracked working tree files would be overwritten by checkout:
packages/dispatcher-converter/test/newtestoldfile.txt
Please move or remove them before you switch branches.
Aborting
```

CQ-4357130 : undo test file deletion
